In [46]:
import numpy as np #importa numpy

In [45]:
from numpy.random import randint #atalho para importar uma função ou objeto

### Introdução aos Arrays

In [8]:
np.array([10, 20, 30]) #Criando array a partir de uma lista

array([10, 20, 30])

In [9]:
np.array([[1,2],[3,4],[5,6]]) #criando uma matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.arange(10) #criando array usando range()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(5) #criando array de zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [12]:
np.zeros((2,3)) #criando matriz de zeros, passando uma tupla com dimensões

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [13]:
np.ones(3) #cria array de 1's, similar à função np.zeros, incluindo criação de matrizes

array([ 1.,  1.,  1.])

In [14]:
np.linspace(1,5,10) #array de valores igualmente espaçados dentro de um intervalo

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [15]:
np.random.rand(4) #cria array de valores aleatórios segundo distribuição normal

array([ 0.13922876,  0.80905222,  0.1293477 ,  0.19816738])

In [16]:
np.random.rand(3,2) #cria matriz de valores aleatórios segundo distribuição normal

array([[ 0.70567297,  0.27663499],
       [ 0.72279407,  0.69890585],
       [ 0.43882974,  0.74044727]])

In [17]:
arr = np.arange(12)

In [19]:
arr.reshape(3,4) #cria uma matriz a partir do array, com as dimensões especificadas

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
arr = randint(10,40,12) #Array de inteiros aleatórios dentro de um intervalo

In [48]:
arr

array([36, 35, 10, 19, 30, 27, 10, 23, 25, 25, 33, 22])

In [49]:
arr.min() #menor valor do array; arr.max() retorna o maior

10

In [50]:
arr.argmin() #posição do menor; argmax() retorna a posição do maior

2

In [51]:
arr.shape #dimensões (para array, somente sua qtde)

(12,)

In [52]:
mat = arr.reshape(3,4)

In [53]:
mat.shape #para matriz, *qtde linhas , qtde colunas)

(3, 4)

### Indexação e seleção em arrays

In [64]:
arr = np.arange(11)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[4] #índexação similar a python

4

In [67]:
arr[3:8] #do índice 3 ao 8-1

array([3, 4, 5, 6, 7])

In [68]:
arr[3:] #3 em diante

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr[:5] #até o 5-1

array([0, 1, 2, 3, 4])

In [71]:
arr[2:5] = 100 #atribuição múltipla

In [72]:
arr

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [73]:
parte_do_array = arr[7:] # *referência* a uma parte do array

In [75]:
parte_do_array

array([ 7,  8,  9, 10])

In [76]:
parte_do_array[:] = 99 #atribuíndo todos os valores

In [77]:
arr #como parte_do_array era referência, então o array de fato é alterado

array([  0,   1, 100, 100, 100,   5,   6,  99,  99,  99,  99])

In [83]:
copia_do_array = arr.copy()[1:7] #cria uma cópia, e não uma referência

In [84]:
copia_do_array

array([  1, 100, 100, 100,   5,   6])

In [87]:
copia_do_array[:] = 200 #a atribuição não muda o array original

In [88]:
arr

array([  0,   1, 100, 100, 100,   5,   6,  99,  99,  99,  99])

In [94]:
mat = np.array([[10,20,32],[32,43,54],[51,67,71]])

In [95]:
mat[2][1] #uma forma de recuperar elemento de uma matriz

67

In [96]:
mat[2,1] #outra forma de recuperar elemento de uma matriz

67

In [100]:
mat[1:3,:2] #usando notação 'slice': linhas 1 até 2 e colunas até 1

array([[32, 43],
       [51, 67]])

In [103]:
arr = np.arange(1,30,3)

In [108]:
bool_array = arr % 2 == 0 #operações booleanas com arrays retornam array de true e false

In [109]:
bool_array

array([False,  True, False,  True, False,  True, False,  True, False,  True], dtype=bool)

In [110]:
arr[bool_array] # cria um subarray somente para as posições 'True'

array([ 4, 10, 16, 22, 28])

In [111]:
arr[arr % 2 == 0] # forma resumida de seleção do exemplo anterior

array([ 4, 10, 16, 22, 28])

In [112]:
arr + 2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])